USE bangalore_pincode_db;

INSERT INTO pincodes (pincode, area, district, state, post_office) VALUES
('560001', 'Bengaluru G.P.O.', 'Bengaluru Urban', 'Karnataka', 'Bengaluru G.P.O.'),
('560001', 'Vidhana Soudha', 'Bengaluru Urban', 'Karnataka', 'Vidhana Soudha S.O'),
('560001', 'Vasanthanagar', 'Bengaluru Urban', 'Karnataka', 'Vasanthanagar S.O'),
('560001', 'Mahatma Gandhi Road', 'Bengaluru Urban', 'Karnataka', 'Mahatma Gandhi Road S.O'),
('560001', 'Dr. Ambedkar Veedhi', 'Bengaluru Urban', 'Karnataka', 'Dr. Ambedkar Veedhi S.O'),
('560002', 'Bangalore City', 'Bengaluru Urban', 'Karnataka', 'Bangalore City H.O'),
('560003', 'Malleswaram', 'Bengaluru Urban', 'Karnataka', 'Malleswaram S.O'),
('560004', 'Basavanagudi', 'Bengaluru Urban', 'Karnataka', 'Basavanagudi H.O'),
('560008', 'H.A.L II Stage', 'Bengaluru Urban', 'Karnataka', 'H.A.L II Stage H.O'),
('560011', 'Jayanagar', 'Bengaluru Urban', 'Karnataka', 'Jayanagar H.O'),
('560017', 'Vimanapura', 'Bengaluru Urban', 'Karnataka', 'Vimanapura S.O'),
('560029', 'Dharmaram College', 'Bengaluru Urban', 'Karnataka', 'Dharmaram College S.O'),
('560034', 'Koramangala', 'Bengaluru Urban', 'Karnataka', 'Koramangala S.O'),
('560034', 'Koramangala I Block', 'Bengaluru Urban', 'Karnataka', 'Koramangala I Block S.O'),
('560034', 'St. Johns Medical College', 'Bengaluru Urban', 'Karnataka', 'St. Johns Medical College S.O'),
('560037', 'Marathahalli Colony', 'Bengaluru Urban', 'Karnataka', 'Marathahalli Colony S.O'),
('560037', 'Doddanekkundi', 'Bengaluru Urban', 'Karnataka', 'Doddanekkundi S.O'),
('560037', 'Kundalahalli', 'Bengaluru Urban', 'Karnataka', 'Kundalahalli S.O'),
('560037', 'Rameshnagar', 'Bengaluru Urban', 'Karnataka', 'Rameshnagar S.O'),
('560038', 'Indiranagar', 'Bengaluru Urban', 'Karnataka', 'Indiranagar S.O'),
('560043', 'Banaswadi', 'Bengaluru Urban', 'Karnataka', 'Banaswadi S.O'),
('560045', 'Arabic College', 'Bengaluru Urban', 'Karnataka', 'Arabic College S.O'),
('560048', 'Mahadevapura', 'Bengaluru Urban', 'Karnataka', 'Mahadevapura S.O'),
('560066', 'Whitefield', 'Bengaluru Urban', 'Karnataka', 'Whitefield S.O'),
('560066', 'Nallurhalli', 'Bengaluru Urban', 'Karnataka', 'Whitefield S.O'),
('560066', 'Pattandur Agrahara', 'Bengaluru Urban', 'Karnataka', 'Whitefield S.O'),
('560066', 'Thubarahalli', 'Bengaluru Urban', 'Karnataka', 'Whitefield S.O'),
('560067', 'Kadugodi', 'Bengaluru Urban', 'Karnataka', 'Kadugodi S.O'),
('560068', 'Bommanahalli', 'Bengaluru Urban', 'Karnataka', 'Bommanahalli S.O'),
('560068', 'Madivala', 'Bengaluru Urban', 'Karnataka', 'Madivala S.O'),
('560068', 'Begur', 'Bengaluru Urban', 'Karnataka', 'Bommanahalli S.O'),
('560068', 'Kudlu', 'Bengaluru Urban', 'Karnataka', 'Bommanahalli S.O'),
('560076', 'Bannerghatta Road', 'Bengaluru Urban', 'Karnataka', 'Bannerghatta Road S.O'),
('560076', 'Mico Layout', 'Bengaluru Urban', 'Karnataka', 'Mico Layout S.O'),
('560095', 'Koramangala VI Bk', 'Bengaluru Urban', 'Karnataka', 'Koramangala VI Bk S.O'),
('560095', 'Koramangala Industrial Layout', 'Bengaluru Urban', 'Karnataka', 'Koramangala Industrial Layout S.O'),
('560102', 'HSR Layout', 'Bengaluru Urban', 'Karnataka', 'HSR Layout S.O')
ON DUPLICATE KEY UPDATE
    area = VALUES(area),
    district = VALUES(district),
    state = VALUES(state),
    post_office = VALUES(post_office);
